### ISSUE TITLE
{PSA] Regarding DLCs

### ISSUE THREAD

**Issue by mantazzo** [LsHallo/ets2-dedicated-convoy-server#13]
Just wanted to make an issue here - as stated by Devs [here in the forums,](https://forum.scssoft.com/viewtopic.php?p=1778671#p1778671) the whole map should always be supported, no matter what you own when you make the server_packages.
I could have misunderstood this though.

**Comment by LsHallo** [comment]
Yeah i also figured as much. Will update the readme.
Thanks for the finding.

**Comment by LsHallo** [comment]
Fixed in [6849884](https://github.com/LsHallo/ets2-dedicated-convoy-server/commit/6849884ce04f139811e25843aebb1306551a4f18)
