### ISSUE TITLE
[ETS2 1.50] error while loading shared libraries: libatomic.so.1, libX11.so.6, libfmod.so.13

### ISSUE THREAD

**Issue by Revoshell** [LsHallo/ets2-dedicated-convoy-server#21]
After updating the ETS2 server I get this error: /app/bin/linux_x64/eurotrucks2_server: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
The required dependencies are already installed.
The ATS server has not yet been updated and it starts without any problems.
I user ubuntu 20.04 (if it matters).
Is this a server problem?

**Comment by H4rry252** [comment]
I have the same problem. After some back and forth (trying to get to 1.50) the error has not occurred recently. But 1.50 still doesn't work.

**Comment by JMeta0** [comment]
I was able to start both ATS and ETS servers. 
As a temporary solution I added GCC to Dockerfile to be installed with apt (it was missing some library that was included in gcc) and I also copied libfmod.so.13 and libfmodstudio.so.13 that someone uploaded on SCS forums - supposedly it is in linux version of ETS.

**Comment by H4rry252** [comment]
Now I tested public_beta and public. In both version this error occurred. But I changed now to temporary_1_50 and the server starts without problems.

**Comment by LsHallo** [comment]
Since I cant really automate the download of libfmod (requires acc) and don't want to rely on external download servers which might not be legit I think I can't release a fix for this. SCS needs to rework the server binaries to not require libfmod. Why would that be needed...
Adding libatomic is not a big problem as you also pointed out. Just installing libatomic1 solves that.
Afterwards l also encountered a missing `libX11.so.6` but that was fixed after installing libx11-dev.

So currently you'll have to patch your own server with libfmod and we'll wait for 1.51 (or 1.50.1).

**Comment by LsHallo** [comment]
I can offer to push a 1.50 tagged image with libatomic1 and libx11-dev installed so you only need to provide libfmod yourself?

**Comment by H4rry252** [comment]
I got problems to install it because the server reboots permanently and there is no stable connection possible. 

I also wondering, why the temporary_1_50 is a 1.49s server

**Comment by LsHallo** [comment]
> I got problems to install it because the server reboots permanently and there is no stable connection possible.

You can change the entrypoint to sleep and the command to infinity. Then the container wont restart and you have free reign inside.
```yaml
services:
  ets2:
    [...]
    entrypoint: sleep
    command: infinity
```
Then run `docker exec --user 0 -it ets2 bash` and you can navigate the container and install dependencies.  

   
> A 1.50 image would be great. But I think this will not serve the required server version. Did you checked this?

That is correct the server would still be downloaded dynamically and the version is not fixed to 1.50.
I can however set the default to download 1.50 automatically. Although it seems temporary_1_50 is not what is says... (See https://github.com/LsHallo/ets2-dedicated-convoy-server/issues/21#issuecomment-2113264882) So no idea how to fix the version number to 1.50.

**Comment by H4rry252** [comment]
> > I got problems to install it because the server reboots permanently and there is no stable connection possible.
> 
> You can change the entrypoint to sleep and the command to infinity. Then the container wont restart and you have free reign inside.
> 
> ```yaml
> services:
>   ets2:
>     [...]
>     entrypoint: sleep
>     command: infinity
> ```
> 
> Then run `docker exec --user 0 -it ets2 bash` and you can navigate the container and install dependencies.
> 
>    
> 
> > A 1.50 image would be great. But I think this will not serve the required server version. Did you checked this?
> 
> That is correct the server would still be downloaded dynamically and the version is not fixed to 1.50. I can however set the default to download 1.50 automatically. Although it seems temporary_1_50 is not what is says... (See [#21 (comment)](https://github.com/LsHallo/ets2-dedicated-convoy-server/issues/21#issuecomment-2113264882)) So no idea how to fix the version number to 1.50.

I will try this but I think not today.

**Comment by LsHallo** [comment]
I also can't really test today. That update is still downloading and won't be finished soon. My amazing internet strikes once again.

The plan for tomorrow is to create a temp fix container with libatomic and libx11 and provide instructions how to deploy ets2 1.50 with libfmod downloaded from their website. I also have the server working now. It reports 1.50s after startup. Only I can't test if I can connect from in game...

**Comment by Revoshell** [comment]
I tried going into the container and installing the libraries manually. The application started to launch. Only now I get an error saying that the server_packages files were not found, although they actually exist.

**Comment by H4rry252** [comment]
It worked. I could connect to the server without problems.

**Comment by LsHallo** [comment]
I have create ats and ets2 server images with libatomic1 and libx11-6 installed.
They are tagged 1.50 on docker hub.

To use them you still need to download libfmod from their [website](https://www.fmod.com/download) (registration required) or some sketchy forum link and place it next to the binary or in LD_LIBRARY_PATH. Alternatively you can download ets2/ats on your linux desktop and copy the libs from there.

I would do the following:
1. Change your image to lshallo/ets2-convoy-server:1.50
2. Mount /app on your host file system: `-v /opt/ets2/app:/app`
3. Make sure the host folder has owner 1000: `chown -R 1000:1000 /opt/ets2/app`
4. Start the container and let it download the server.
5. Stop the server
6. Copy the libfmod and libfmodstudio files to `/opt/ets2/app/bin/linux_x64`
7. Start the server and enjoy

**Comment by LsHallo** [comment]
It seems they have updated the image and libfmod is no longer required. I'm going to update the image to include libatomic and libx11. My server starts with that config without libfmod.
