### ISSUE TITLE
libatomic error still persists

### ISSUE THREAD

**Issue by LsHallo** [LsHallo/ets2-dedicated-convoy-server#24]
I've installed a new ETS2 dedicated server and the libatomic error remains. My system is linux based, QNAP (AMD). In the past the container worked, then came the libatomic problem and it seems it's not gone.

######################
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1948160' already up to date.
[INFO]: Update done.
[INFO]: Starting server...
/app/bin/linux_x64/eurotrucks2_server: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
[INFO]: Writing config file...
[INFO]: Config file written.
[INFO]: Updating ETS Server...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1716584438
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '1948160' already up to date.
[INFO]: Update done.
[INFO]: Starting server...
/app/bin/linux_x64/eurotrucks2_server: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

_Originally posted by @mklengel in https://github.com/LsHallo/ets2-dedicated-convoy-server/pull/23#issuecomment-2141851088_

**Comment by LsHallo** [comment]
Can you provide the output of `docker image inspect lshallo/ets2-convoy-server`
Particularly interested in the label `org.opencontainers.image.version`

**Comment by LsHallo** [comment]
As I suspected. Your image is still v0.3.2 and does not include libatomic. You need to pull the image again to get v0.3.3 which includes libatomic.

**Comment by mklengel** [comment]
Seems my fault. I stopped+removed+installed+started the container. Assumed it pulls the image again. It seems I have to learn some more Docker stuff. Thx for the quick answer.

**Comment by mklengel** [comment]
It works now without problems. Thx again
