### ISSUE TITLE
Server with more than 8 players not visible

### ISSUE THREAD

**Issue by LsHallo** [LsHallo/ets2-dedicated-convoy-server#27]
I can't see the server I created using the workaround in the server finder.
Neither session search ID nor server name works.

With 8 players I can find the server without issue.

I'm just creating this issue to pre-empt anyone creating it. It's known but I don't know how to circumvent.

Follow up to #22

**Comment by 327-LIVE** [comment]
J'ai trouvé.

Si vous avez la console dans le jeu d'activée avec la touche ², faite la apparaitre et taper cette commende : g_max_convoy_size 128

Chercher a nouveau les serveurs, il devrait apparaitre. Le jeu sauvegardera la configuration et il ne sera pas utile de le faire au démarrage suivent :) 

Pour information le serveur sélectionner est le mien :) 
![ets2server](https://github.com/user-attachments/assets/aca81a91-235f-47bf-8d5b-13964aebd46a)

**Comment by LsHallo** [comment]
Nice find. Makes sense that the game has the same setting as the server. Will add this to the readme.

**Comment by 327-LIVE** [comment]
il faudra expliquer ou donner ce lien pour permettre au personnes de pouvoir jouer sur les serveurs 128 joueurs

https://forum.scssoft.com/viewtopic.php?p=102815#p102815

**Comment by LsHallo** [comment]
I have added the explanation to the README
