### ISSUE TITLE
Support for ATS 1.51

### ISSUE THREAD

**Issue by newton21989** [LsHallo/ets2-dedicated-convoy-server#28]
Cannot connect to server after 1.51 update, using latest tag as of posting.

**Comment by LsHallo** [comment]
Please share your setup, how you run the container and the complete log output of the container here for debugging purposes.

**Comment by LsHallo** [comment]
I can connect to my server using the latest ATS. And since you haven't responded to my first inquiry I would expect you have also found a way to connect to your server. If you still have the problem you can reopen the issue here.
