### ISSUE TITLE
steam service

### ISSUE THREAD

**Issue by DasShorty** [LsHallo/ets2-dedicated-convoy-server#9]
Hey, i tried using your minimal server start command but i got this error as i executed it.

How can i get rid of this error?

Log:
https://pastes.dev/jsC7N9G8a9

**Comment by LsHallo** [comment]
Thanks for your report.
I have reproduced your issue. I think some file might have moved and I need to update the LD_LIBRARY_PATH again.
Will have a look at this later.

**Comment by LsHallo** [comment]
Ok turns out after I refreshed my game token I can no longer recreate the issue.
My full log until server start is available here: https://pastes.dev/5nSJSprRzQ

Can you try to start the server without any volume mounts?

**Comment by LsHallo** [comment]
This issue also relates to the missing `steamservice.so`: https://github.com/parkervcp/eggs/issues/2302  
But they also say to ignore the error.

**Comment by DasShorty** [comment]
I started the server without an mounting and it works. I also added an steam server token to it

**Comment by LsHallo** [comment]
Okay. I would recommend not using a mount for /app. Only mount the .local for custom server packages. It does not save any data anyways.

**Comment by DasShorty** [comment]
ah okay thx
